---
text_file: ""
nogui: false
test: false
random_seed: 0
max_ep_len: 2000
action_std: 0.8
action_std_decay_rate: 0.05
min_action_std: 0.05
action_std_decay_freq: 15000
update_timestep: 20000
K_epochs: 300
eps_clip: 0.2
gamma: 0.99
lr_actor: 0.0001
lr_critic: 0.003
total_test_episodes: 990
total_train_episodes: 5000
mode: "Plain"
testSeed: null
delay: null
has_continuous_action_space: True  
max_training_timesteps: 360000   
print_freq: ${max_ep_len} * 10       
log_freq: ${max_ep_len} * 2          
save_model_freq: 5000        
hidden_size: 50
