---
defaults:
  - override hydra/launcher: joblib
hydra:
  job:
    chdir: false
text_file: ""
nogui: True
test: false
random_seed: 001
max_ep_len: 2000
gamma: 0.99
PPO:
  action_std: 0.8
  action_std_decay_rate: 0.05
  min_action_std: 0.05
  action_std_decay_freq: 20000
  update_timestep: 20000
  K_epochs: 300
  eps_clip: 0.2
  lr_actor: 0.0001
  lr_critic: 0.003
DQN:
  lr: 0.001
  epsilon: 0.1
  batch_size: 128
  target_iter_replace: 8000
TD3:
  policy_noise: 0.2
  noise_clip: 0.5
  policy_freq: 2
  tau: 0.005
  start_timesteps: 25000
  expl_noise: 0.1
  batch_size: 256

total_test_episodes: 998
mode: "SLSC"
delay: 1
has_continuous_action_space: True  
max_training_timesteps: 300000   
log_freq: ${max_ep_len} * 2          
save_model_freq: 5000     
memory_capacity: 20000   
hidden_size: 50
